# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e5ce850a5c52e1c105a77f6e02ce7964"
application_url = "https://losses-weak-risk-exempt.trycloudflare.com"
embedded = true
name = "sizechart"
handle = "sizechart-17"

[build]
include_config_on_deploy = true
dev_store_url = "boostskill.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://losses-weak-risk-exempt.trycloudflare.com/auth/callback",
  "https://losses-weak-risk-exempt.trycloudflare.com/auth/shopify/callback",
  "https://losses-weak-risk-exempt.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
