# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e7a784a36ed1426c8ebdf10e329f3e16"
application_url = "https://omaha-buddy-blowing-should.trycloudflare.com"
embedded = true
name = "SizeChart"
handle = "sizechart-18"

[build]
include_config_on_deploy = true
dev_store_url = "sizecharttesting.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [
  "https://omaha-buddy-blowing-should.trycloudflare.com/auth/callback",
  "https://omaha-buddy-blowing-should.trycloudflare.com/auth/shopify/callback",
  "https://omaha-buddy-blowing-should.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
