# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f688020ac7ef80f5265e91390e8b80a4"
application_url = "https://example.com/"
embedded = true
name = "sizechart"
handle = "sizechart-17"

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "boostskill.myshopify.com"
automatically_update_urls_on_dev = false
